"""empty message

Revision ID: 2e050c6f70fc
Revises: e328a424dd26
Create Date: 2021-05-12 11:01:27.861374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e050c6f70fc'
down_revision = 'e328a424dd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('shows', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'shows')
    # ### end Alembic commands ###
