"""empty message

Revision ID: 64e7b4293c2a
Revises: 06e92a6e68c3
Create Date: 2021-05-10 16:28:50.128150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64e7b4293c2a'
down_revision = '06e92a6e68c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', sa.Text(length=50), nullable=True))
    op.drop_column('comment', 'course_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('course_name', mysql.TINYTEXT(), nullable=True))
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###
