"""empty message

Revision ID: aef8257a7b96
Revises: d9dccbc84685
Create Date: 2021-05-14 00:45:37.994684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aef8257a7b96'
down_revision = 'd9dccbc84685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividad')
    op.add_column('user', sa.Column('img_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img_name')
    op.create_table('actividad',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('activity_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('activity_description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('activity_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date_start', mysql.DATETIME(), nullable=True),
    sa.Column('date_finish', mysql.DATETIME(), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='actividad_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='actividad_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
