"""empty message

Revision ID: e328a424dd26
Revises: 64e7b4293c2a
Create Date: 2021-05-12 10:16:42.943775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e328a424dd26'
down_revision = '64e7b4293c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'date_created')
    # ### end Alembic commands ###
